apply plugin: 'com.android.application'

android {
    namespace 'com.urmitechnology.employeeapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.urmitechnology.employeeapp'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }
    dependencies {
        implementation 'com.google.android.gms:play-services-location:21.3.0'
        implementation 'androidx.core:core:1.15.0'

    }
}

